name: 'Env File to K8s Secret'
description: 'Converts your .env file (base64 encoded already) to k8s Secret file on the fly'
inputs:
  k8sName:
    description: 'Name of the secret object'
    required: true
  k8sNamespace:
    description: 'Namespace of the secret object'
    required: false
    default: 'default'
  base64EncodedEnvString:
    description: 'Env file in base64 encoded string format'
    required: true
outputs:
  k8sObject:
    description: 'created k8s object'
runs:
  using: 'docker'
  image: 'docker://timowang1991/github-actions-envfile-to-k8s-secret'
  args:
    - ${{ inputs.k8sName }}
    - ${{ inputs.k8sNamespace }}
    - ${{ inputs.base64EncodedEnvString }}