name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - id: 'generateConfigMap'
        name: Generate ConfigMap
        uses: timowang1991/github-actions-envfile-to-k8s-configmap-or-secret@v3
        with:
          k8sName: 'test-configmap'
          k8sKind: 'ConfigMap'
          base64EncodedEnvString: ${{ secrets.ENV }}
      
      - name: Check ConfigMap
        run: echo ${{ steps.generateConfigMap.outputs.k8sObject }}
