name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - id: 'test-configmap'
        name: Test ConfigMap
        uses: timowang1991/github-actions-envfile-to-k8s-configmap-or-secret@v1
        with:
          name: 'test-configmap'
          kind: 'ConfigMap'
          base64EncodedEnvString: ${{ secret.ENV }}
      
      - name: Check ConfigMap
        run: echo ${{ 'test-configmap'.output.k8sObject }}
