name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'generateSecret'
        name: Generate Secret
        uses: timowang1991/github-actions-envfile-to-k8s-object@v1
        with:
          k8sName: 'my-secret'
          k8sNamespace: 'my-namespace'
          base64EncodedEnvString: ${{ secrets.ENV }}
      
      - name: Check Secret
        run: |
          echo "${{ steps.generateSecret.outputs.k8sObject }}"

      - name: Output Secret to a yaml file
        run: |
          echo "${{ steps.generateSecret.outputs.k8sObject }}" > secret.yaml
          cat secret.yaml
